// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD761wed_pWzthC1l_Mk-K-x-Xe89LZsz0',
    appId: '1:684154371628:android:121519d8aea18971859b89',
    messagingSenderId: '684154371628',
    projectId: 'iserve-19705',
    databaseURL: 'https://iserve-19705-default-rtdb.firebaseio.com',
    storageBucket: 'iserve-19705.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQzTOhGw_58W81Upz2P2D5ybmVRAVYg6I',
    appId: '1:684154371628:ios:476bba84d21abccc859b89',
    messagingSenderId: '684154371628',
    projectId: 'iserve-19705',
    databaseURL: 'https://iserve-19705-default-rtdb.firebaseio.com',
    storageBucket: 'iserve-19705.appspot.com',
    iosClientId: '684154371628-01v540g7mmn550eosss0a37j8f3ppf21.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudTemplate1',
  );
}
